use portfolio
insert into asset_name_symbol values (1, 'NIO', 'NIO Limited', '1');
insert into asset_name_symbol values (2, 'AAPL', 'Apple Inc.', '1');
insert into asset_name_symbol values (3, 'VIAC', 'ViacomCBS Inc.', '1');
insert into asset_name_symbol values (4, 'TME', 'Tencent Music Entertainment Group', '1');
insert into asset_name_symbol values (5, 'CLF', 'Cleveland-Cliffs Inc.', '1');
insert into asset_name_symbol values (6, 'PLTR', 'Palantir Technologies Inc.', '1');
insert into asset_name_symbol values (7, 'F', 'Ford Motor Company', '1');
insert into asset_name_symbol values (8, 'GE', 'General Electric Company', '1');
insert into asset_name_symbol values (9, 'MVIS', 'MicroVision', '1');
insert into asset_name_symbol values (10, 'X', 'United States Steel Corporation', '1');
insert into asset_name_symbol values (11, 'ITUB', 'Itaú Unibanco Holding S.A.', '1');
insert into asset_name_symbol values (12, 'AMD', 'Advanced Micro Devices', '1');
insert into asset_name_symbol values (13, 'BAC', 'Bank of America Corporation', '1');
insert into asset_name_symbol values (14, 'PLUG', 'Plug Power Inc.', '1');
insert into asset_name_symbol values (15, 'T', 'AT&T Inc.', '1');
insert into asset_name_symbol values (16, 'MARA', 'Marathon Digital Holdings', '1');
insert into asset_name_symbol values (17, 'BB', 'BlackBerry Limited', '1');
insert into asset_name_symbol values (18, 'MSFT', 'Microsoft Corporation', '1');
insert into asset_name_symbol values (19, 'TSLA', 'Tesla', '1');
insert into asset_name_symbol values (20, 'DISCA', 'Discovery', '1');
insert into asset_name_symbol values (21, 'AMC', 'AMC Entertainment Holdings', '1');
insert into asset_name_symbol values (22, 'IQ', 'iQIYI', '1');
insert into asset_name_symbol values (23, 'AAL', 'American Airlines Group Inc.', '1');
insert into asset_name_symbol values (24, 'FCEL', 'FuelCell Energy', '1');
insert into asset_name_symbol values (25, 'PBR', 'Petróleo Brasileiro S.A. - Petrobras', '1');
insert into asset_name_symbol values (26, 'GGB', 'Gerdau S.A.', '1');
insert into asset_name_symbol values (27, 'INTC', 'Intel Corporation', '1');
insert into asset_name_symbol values (28, 'VALE', 'Vale S.A.', '1');
insert into asset_name_symbol values (29, 'SNAP', 'Snap Inc.', '1');
insert into asset_name_symbol values (30, 'XPEV', 'XPeng Inc.', '1');
insert into asset_name_symbol values (31, 'CHWY', 'Chewy', '1');
insert into asset_name_symbol values (32, 'TIGR', 'UP Fintech Holding Limited', '1');
insert into asset_name_symbol values (33, 'BBD', 'Banco Bradesco S.A.', '1');
insert into asset_name_symbol values (34, 'TLRY', 'Tilray', '1');
insert into asset_name_symbol values (35, 'WFC', 'Wells Fargo & Company', '1');
insert into asset_name_symbol values (36, 'PFE', 'Pfizer Inc.', '1');
insert into asset_name_symbol values (37, 'RIOT', 'Riot Blockchain', '1');
insert into asset_name_symbol values (38, 'CCL', 'Carnival Corporation & plc', '1');
insert into asset_name_symbol values (39, 'VIPS', 'Vipshop Holdings Limited', '1');
insert into asset_name_symbol values (40, 'MU', 'Micron Technology', '1');
insert into asset_name_symbol values (41, 'XOM', 'Exxon Mobil Corporation', '1');
insert into asset_name_symbol values (42, 'GM', 'General Motors Company', '1');
insert into asset_name_symbol values (43, 'CS', 'Credit Suisse Group AG', '1');
insert into asset_name_symbol values (44, 'NOK', 'Nokia Corporation', '1');
insert into asset_name_symbol values (45, 'CHPT', 'Chargepoint Holdings Inc.', '1');
insert into asset_name_symbol values (46, 'GSX', 'GSX Techedu Inc.', '1');
insert into asset_name_symbol values (47, 'BIDU', 'Baidu', '1');
insert into asset_name_symbol values (48, 'CAN', 'Canaan Inc.', '1');
insert into asset_name_symbol values (49, 'KR', 'The Kroger Co.', '1');
insert into asset_name_symbol values (50, 'MRO', 'Marathon Oil Corporation', '1');
insert into asset_name_symbol values (51, 'AMAT', 'Applied Materials', '1');
insert into asset_name_symbol values (52, 'SIRI', 'Sirius XM Holdings Inc.', '1');
insert into asset_name_symbol values (53, 'FB', 'Facebook', '1');
insert into asset_name_symbol values (54, 'BNGO', 'Bionano Genomics', '1');
insert into asset_name_symbol values (55, 'CMCSA', 'Comcast Corporation', '1');
insert into asset_name_symbol values (56, 'APHA', 'Aphria Inc.', '1');
insert into asset_name_symbol values (57, 'CSCO', 'Cisco Systems', '1');
insert into asset_name_symbol values (58, 'ET', 'Energy Transfer LP', '1');
insert into asset_name_symbol values (59, 'CCIV', 'Churchill Capital Corp IV', '1');
insert into asset_name_symbol values (60, 'FUTU', 'Futu Holdings Limited', '1');
insert into asset_name_symbol values (61, 'FUBO', 'fuboTV Inc.', '1');
insert into asset_name_symbol values (62, 'BABA', 'Alibaba Group Holding Limited', '1');
insert into asset_name_symbol values (63, 'CX', 'CEMEX', '1');
insert into asset_name_symbol values (64, 'LI', 'Li Auto Inc.', '1');
insert into asset_name_symbol values (65, 'SQ', 'Square', '1');
insert into asset_name_symbol values (66, 'FCX', 'Freeport-McMoRan Inc.', '1');
insert into asset_name_symbol values (67, 'GOLD', 'Barrick Gold Corporation', '1');
insert into asset_name_symbol values (68, 'BA', 'The Boeing Company', '1');
insert into asset_name_symbol values (69, 'RIG', 'Transocean Ltd.', '1');
insert into asset_name_symbol values (70, 'EDU', 'New Oriental Education & Technology Group Inc.', '1');
insert into asset_name_symbol values (71, 'VZ', 'Verizon Communications Inc.', '1');
insert into asset_name_symbol values (72, 'OXY', 'Occidental Petroleum Corporation', '1');
insert into asset_name_symbol values (73, 'BFT', 'Foley Trasimene Acquisition Corp. II', '1');
insert into asset_name_symbol values (74, 'GOEV', 'Canoo Inc.', '1');
insert into asset_name_symbol values (75, 'UBER', 'Uber Technologies', '1');
insert into asset_name_symbol values (76, 'C', 'Citigroup Inc.', '1');
insert into asset_name_symbol values (77, 'SKLZ', 'Skillz Inc.', '1');
insert into asset_name_symbol values (78, 'JPM', 'JPMorgan Chase & Co.', '1');
insert into asset_name_symbol values (79, 'NLY', 'Annaly Capital Management', '1');
insert into asset_name_symbol values (80, 'KGC', 'Kinross Gold Corporation', '1');
insert into asset_name_symbol values (81, 'NKLA', 'Nikola Corporation', '1');
insert into asset_name_symbol values (82, 'WBA', 'Walgreens Boots Alliance', '1');
insert into asset_name_symbol values (83, 'NCLH', 'Norwegian Cruise Line Holdings Ltd.', '1');
insert into asset_name_symbol values (84, 'KMI', 'Kinder Morgan', '1');
insert into asset_name_symbol values (85, 'KO', 'The Coca-Cola Company', '1');
insert into asset_name_symbol values (86, 'TWTR', 'Twitter', '1');
insert into asset_name_symbol values (87, 'ABEV', 'Ambev S.A.', '1');
insert into asset_name_symbol values (88, 'FSR', 'Fisker Inc.', '1');
insert into asset_name_symbol values (89, 'VTRS', 'Viatris Inc.', '1');
insert into asset_name_symbol values (90, 'KEY', 'KeyCorp', '1');
insert into asset_name_symbol values (91, 'ZNGA', 'Zynga Inc.', '1');
insert into asset_name_symbol values (92, 'RKT', 'Rocket Companies', '1');
insert into asset_name_symbol values (93, 'UAL', 'United Airlines Holdings', '1');
insert into asset_name_symbol values (94, 'UA', 'Under Armour', '1');
insert into asset_name_symbol values (95, 'BP', 'BP p.l.c.', '1');
insert into asset_name_symbol values (96, 'MRK', 'Merck & Co.', '1');
insert into asset_name_symbol values (97, 'HPE', 'Hewlett Packard Enterprise Company', '1');
insert into asset_name_symbol values (98, 'DKNG', 'DraftKings Inc.', '1');
insert into asset_name_symbol values (99, 'MRNA', 'Moderna', '1');
insert into asset_name_symbol values (100, 'BMY', 'Bristol-Myers Squibb Company', '1');
insert into asset_name_symbol values (101, 'MS', 'Morgan Stanley', '1');
insert into asset_name_symbol values (102, 'HBAN', 'Huntington Bancshares Incorporated', '1');
insert into asset_name_symbol values (103, 'FTCH', 'Farfetch Limited', '1');
insert into asset_name_symbol values (104, 'SLB', 'Schlumberger Limited', '1');
insert into asset_name_symbol values (105, 'TSM', 'Taiwan Semiconductor Manufacturing Company Limited', '1');
insert into asset_name_symbol values (106, 'SWN', 'Southwestern Energy Company', '1');
insert into asset_name_symbol values (107, 'MT', 'ArcelorMittal', '1');
insert into asset_name_symbol values (108, 'DISCK', 'Discovery', '1');
insert into asset_name_symbol values (109, 'PSLV', 'Sprott Physical Silver Trust', '1');
insert into asset_name_symbol values (110, 'JD', 'JD.com', '1');
insert into asset_name_symbol values (111, 'AUY', 'Yamana Gold Inc.', '1');
insert into asset_name_symbol values (112, 'MRVL', 'Marvell Technology Group Ltd.', '1');
insert into asset_name_symbol values (113, 'PINS', 'Pinterest', '1');
insert into asset_name_symbol values (114, 'SPCE', 'Virgin Galactic Holdings', '1');
insert into asset_name_symbol values (115, 'CIG', 'Companhia Energética de Minas Gerais', '1');
insert into asset_name_symbol values (116, 'GSAT', 'Globalstar', '1');
insert into asset_name_symbol values (117, 'PCG', 'PG&E Corporation', '1');
insert into asset_name_symbol values (118, 'GME', 'GameStop Corp.', '1');
insert into asset_name_symbol values (119, 'DVN', 'Devon Energy Corporation', '1');
insert into asset_name_symbol values (120, 'ING', 'ING Groep N.V.', '1');
insert into asset_name_symbol values (121, 'QS', 'QuantumScape Corporation', '1');
insert into asset_name_symbol values (122, 'ROOT', 'Root', '1');
insert into asset_name_symbol values (123, 'INFY', 'Infosys Limited', '1');
insert into asset_name_symbol values (124, 'DAL', 'Delta Air Lines', '1');
insert into asset_name_symbol values (125, 'OPEN', 'Opendoor Technologies Inc.', '1');
insert into asset_name_symbol values (126, 'CVE', 'Cenovus Energy Inc.', '1');
insert into asset_name_symbol values (127, 'JMIA', 'Jumia Technologies AG', '1');
insert into asset_name_symbol values (128, 'ORCL', 'Oracle Corporation', '1');
insert into asset_name_symbol values (129, 'BTG', 'B2Gold Corp.', '1');
insert into asset_name_symbol values (130, 'ABBV', 'AbbVie Inc.', '1');
insert into asset_name_symbol values (131, 'NVDA', 'NVIDIA Corporation', '1');
insert into asset_name_symbol values (132, 'HPQ', 'HP Inc.', '1');
insert into asset_name_symbol values (133, 'COP', 'ConocoPhillips', '1');
insert into asset_name_symbol values (134, 'HL', 'Hecla Mining Company', '1');
insert into asset_name_symbol values (135, 'TSNPD', 'HUMBL', '1');
insert into asset_name_symbol values (136, 'PBR-A', 'Petróleo Brasileiro S.A. - Petrobras', '1');
insert into asset_name_symbol values (137, 'AA', 'Alcoa Corporation', '1');
insert into asset_name_symbol values (138, 'MO', 'Altria Group', '1');
insert into asset_name_symbol values (139, 'V', 'Visa Inc.', '1');
insert into asset_name_symbol values (140, 'FNMA', 'Federal National Mortgage Association', '1');
insert into asset_name_symbol values (141, 'CVX', 'Chevron Corporation', '1');
insert into asset_name_symbol values (142, 'RLLCF', 'Rolls-Royce Holdings plc', '1');
insert into asset_name_symbol values (143, 'WMT', 'Walmart Inc.', '1');
insert into asset_name_symbol values (144, 'AMRS', 'Amyris', '1');
insert into asset_name_symbol values (145, 'JBLU', 'JetBlue Airways Corporation', '1');
insert into asset_name_symbol values (146, 'PG', 'The Procter & Gamble Company', '1');
insert into asset_name_symbol values (147, 'AZN', 'AstraZeneca PLC', '1');
insert into asset_name_symbol values (148, 'DOX', 'Amdocs Limited', '1');
insert into asset_name_symbol values (149, 'PTON', 'Peloton Interactive', '1');
insert into asset_name_symbol values (150, 'ON', 'ON Semiconductor Corporation', '1');
insert into asset_name_symbol values (151, 'MOS', 'The Mosaic Company', '1');
insert into asset_name_symbol values (152, 'RUN', 'Sunrun Inc.', '1');
insert into asset_name_symbol values (153, 'RF', 'Regions Financial Corporation', '1');
insert into asset_name_symbol values (154, 'LUMN', 'Lumen Technologies', '1');
insert into asset_name_symbol values (155, 'GILD', 'Gilead Sciences', '1');
insert into asset_name_symbol values (156, 'EBAY', 'eBay Inc.', '1');
insert into asset_name_symbol values (157, 'CCJ', 'Cameco Corporation', '1');
insert into asset_name_symbol values (158, 'DB', 'Deutsche Bank Aktiengesellschaft', '1');
insert into asset_name_symbol values (159, 'PYPL', 'PayPal Holdings', '1');
insert into asset_name_symbol values (160, 'QCOM', 'QUALCOMM Incorporated', '1');
insert into asset_name_symbol values (161, 'DIS', 'The Walt Disney Company', '1');
insert into asset_name_symbol values (162, 'NEE', 'NextEra Energy', '1');
insert into asset_name_symbol values (163, 'EPD', 'Enterprise Products Partners L.P.', '1');
insert into asset_name_symbol values (164, 'HMBL', 'HUMBL', '1');
insert into asset_name_symbol values (165, 'MGM', 'MGM Resorts International', '1');
insert into asset_name_symbol values (166, 'GFI', 'Gold Fields Limited', '1');
insert into asset_name_symbol values (167, 'TAL', 'TAL Education Group', '1');
insert into asset_name_symbol values (168, 'GSK', 'GlaxoSmithKline plc', '1');
insert into asset_name_symbol values (169, 'HMY', 'Harmony Gold Mining Company Limited', '1');
insert into asset_name_symbol values (170, 'EQT', 'EQT Corporation', '1');
insert into asset_name_symbol values (171, 'BCS', 'Barclays PLC', '1');
insert into asset_name_symbol values (172, 'CARR', 'Carrier Global Corporation', '1');
insert into asset_name_symbol values (173, 'NEM', 'Newmont Corporation', '1');
insert into asset_name_symbol values (174, 'PS', 'Pluralsight', '1');
insert into asset_name_symbol values (175, 'CRM', 'salesforce.com', '1');
insert into asset_name_symbol values (176, 'IBN', 'ICICI Bank Limited', '1');
insert into asset_name_symbol values (177, 'MDLZ', 'Mondelez International', '1');
insert into asset_name_symbol values (178, 'WMB', 'The Williams Companies', '1');
insert into asset_name_symbol values (179, 'HAL', 'Halliburton Company', '1');
insert into asset_name_symbol values (180, 'COTY', 'Coty Inc.', '1');
insert into asset_name_symbol values (181, 'PPL', 'PPL Corporation', '1');
insert into asset_name_symbol values (182, 'FOXA', 'Fox Corporation', '1');
insert into asset_name_symbol values (183, 'SRNE', 'Sorrento Therapeutics', '1');
insert into asset_name_symbol values (184, 'AMCR', 'Amcor plc', '1');
insert into asset_name_symbol values (185, 'RDS-A', 'Royal Dutch Shell plc', '1');
insert into asset_name_symbol values (186, 'RLX', 'RLX Technology Inc.', '1');
insert into asset_name_symbol values (187, 'SCHW', 'The Charles Schwab Corporation', '1');
insert into asset_name_symbol values (188, 'SAN', 'Banco Santander', '1');
insert into asset_name_symbol values (189, 'LYFT', 'Lyft', '1');
insert into asset_name_symbol values (190, 'NRZ', 'New Residential Investment Corp.', '1');
insert into asset_name_symbol values (191, 'RYCEY', 'Rolls-Royce Holdings plc', '1');
insert into asset_name_symbol values (192, 'COG', 'Cabot Oil & Gas Corporation', '1');
insert into asset_name_symbol values (193, 'CLDR', 'Cloudera', '1');
insert into asset_name_symbol values (194, 'CPG', 'Crescent Point Energy Corp.', '1');
insert into asset_name_symbol values (195, 'KDP', 'Keurig Dr Pepper Inc.', '1');
insert into asset_name_symbol values (196, 'BTC-USD', 'Bitcoin USD', '2');
insert into asset_name_symbol values (197, 'ETH-USD', 'Ethereum USD', '2');
insert into asset_name_symbol values (198, 'BNB-USD', 'BinanceCoin USD', '2');
insert into asset_name_symbol values (199, 'USDT-USD', 'Tether USD', '2');
insert into asset_name_symbol values (200, 'ADA-USD', 'Cardano USD', '2');
insert into asset_name_symbol values (201, 'DOT1-USD', 'Polkadot USD', '2');
insert into asset_name_symbol values (202, 'XRP-USD', 'XRP USD', '2');
insert into asset_name_symbol values (203, 'LTC-USD', 'Litecoin USD', '2');
insert into asset_name_symbol values (204, 'THETA-USD', 'THETA USD', '2');
insert into asset_name_symbol values (205, 'LINK-USD', 'Chainlink USD', '2');
insert into asset_name_symbol values (206, 'USDC-USD', 'USDCoin USD', '2');
insert into asset_name_symbol values (207, 'BCH-USD', 'BitcoinCash USD', '2');
insert into asset_name_symbol values (208, 'XLM-USD', 'Stellar USD', '2');
insert into asset_name_symbol values (209, 'LUNA1-USD', 'Terra USD', '2');
insert into asset_name_symbol values (210, 'DOGE-USD', 'Dogecoin USD', '2');
insert into asset_name_symbol values (211, 'TRX-USD', 'TRON USD', '2');
insert into asset_name_symbol values (212, 'VET-USD', 'VeChain USD', '2');
insert into asset_name_symbol values (213, 'SOL1-USD', 'Solana USD', '2');
insert into asset_name_symbol values (214, 'EOS-USD', 'EOS USD', '2');
insert into asset_name_symbol values (215, 'XMR-USD', 'Monero USD', '2');
insert into asset_name_symbol values (216, 'MIOTA-USD', 'IOTA USD', '2');
insert into asset_name_symbol values (217, 'ATOM1-USD', 'Cosmos USD', '2');
insert into asset_name_symbol values (218, 'KSM-USD', 'Kusama USD', '2');
insert into asset_name_symbol values (219, 'BSV-USD', 'BitcoinSV USD', '2');
insert into asset_name_symbol values (220, 'XTZ-USD', 'Tezos USD', '2');
insert into asset_name_symbol values (221, 'AVAX-USD', 'Avalanche USD', '2');
insert into asset_name_symbol values (222, 'NEO-USD', 'NEO USD', '2');
insert into asset_name_symbol values (223, 'ALGO-USD', 'Algorand USD', '2');
insert into asset_name_symbol values (224, 'CTC1-USD', 'Creditcoin USD', '2');
insert into asset_name_symbol values (225, 'XEM-USD', 'NEM USD', '2');
insert into asset_name_symbol values (226, 'HBAR-USD', 'HederaHashgraph USD', '2');
insert into asset_name_symbol values (227, 'EGLD-USD', 'Elrond USD', '2');
insert into asset_name_symbol values (228, 'DCR-USD', 'Decred USD', '2');
insert into asset_name_symbol values (229, 'TFUEL-USD', 'ThetaFuel USD', '2');
insert into asset_name_symbol values (230, 'DASH-USD', 'Dash USD', '2');
insert into asset_name_symbol values (231, 'ZIL-USD', 'Zilliqa USD', '2');
insert into asset_name_symbol values (232, 'ICX-USD', 'ICON USD', '2');
insert into asset_name_symbol values (233, 'ZEC-USD', 'Zcash USD', '2');
insert into asset_name_symbol values (234, 'BAT-USD', 'BasicAttentionToken USD', '2');
insert into asset_name_symbol values (235, 'ONE2-USD', 'Harmony USD', '2');
insert into asset_name_symbol values (236, 'CCXX-USD', 'CounosX USD', '2');
insert into asset_name_symbol values (237, 'ETC-USD', 'EthereumClassic USD', '2');
insert into asset_name_symbol values (238, 'RVN-USD', 'Ravencoin USD', '2');
insert into asset_name_symbol values (239, 'ZRX-USD', '0x USD', '2');
insert into asset_name_symbol values (240, 'DFI-USD', 'DeFiChain USD', '2');
insert into asset_name_symbol values (241, 'ONT-USD', 'Ontology USD', '2');
insert into asset_name_symbol values (242, 'STX1-USD', 'Stacks USD', '2');
insert into asset_name_symbol values (243, 'BNT-USD', 'Bancor USD', '2');
insert into asset_name_symbol values (244, 'SC-USD', 'Siacoin USD', '2');
insert into asset_name_symbol values (245, 'WAVES-USD', 'Waves USD', '2');
insert into asset_name_symbol values (246, 'CEL-USD', 'Celsius USD', '2');
insert into asset_name_symbol values (247, 'AR-USD', 'Arweave USD', '2');
insert into asset_name_symbol values (248, 'OMG-USD', 'OmiseGO USD', '2');
insert into asset_name_symbol values (249, 'XWC-USD', 'WhiteCoin USD', '2');
insert into asset_name_symbol values (250, 'VGX-USD', 'VoyagerToken USD', '2');
insert into asset_name_symbol values (251, 'DGB-USD', 'DigiByte USD', '2');
insert into asset_name_symbol values (252, 'CKB-USD', 'NervosNetwork USD', '2');
insert into asset_name_symbol values (253, 'QTUM-USD', 'Qtum USD', '2');
insert into asset_name_symbol values (254, 'IOST-USD', 'IOST USD', '2');
insert into asset_name_symbol values (255, 'CELO-USD', 'Celo USD', '2');
insert into asset_name_symbol values (256, 'HNT1-USD', 'Helium USD', '2');
insert into asset_name_symbol values (257, 'LSK-USD', 'Lisk USD', '2');
insert into asset_name_symbol values (258, 'STORJ-USD', 'Storj USD', '2');
insert into asset_name_symbol values (259, 'XVG-USD', 'Verge USD', '2');
insert into asset_name_symbol values (260, 'BTG-USD', 'BitcoinGold USD', '2');
insert into asset_name_symbol values (261, 'NANO-USD', 'Nano USD', '2');
insert into asset_name_symbol values (262, 'LRC-USD', 'Loopring USD', '2');
insert into asset_name_symbol values (263, 'GLM-USD', 'Golem USD', '2');
insert into asset_name_symbol values (264, 'ETN-USD', 'Electroneum USD', '2');
insert into asset_name_symbol values (265, 'KNC-USD', 'KyberNetwork USD', '2');
insert into asset_name_symbol values (266, 'ZEN-USD', 'Horizen USD', '2');
insert into asset_name_symbol values (267, 'WAXP-USD', 'WAX USD', '2');
insert into asset_name_symbol values (268, 'EWT-USD', 'EnergyWebToken USD', '2');
insert into asset_name_symbol values (269, 'SNT-USD', 'Status USD', '2');
insert into asset_name_symbol values (270, 'XDC-USD', 'XinFinNetwork USD', '2');
insert into asset_name_symbol values (271, 'STEEM-USD', 'Steem USD', '2');
insert into asset_name_symbol values (272, 'REP-USD', 'Augur USD', '2');
insert into asset_name_symbol values (273, 'IOTX-USD', 'IoTeX USD', '2');
insert into asset_name_symbol values (274, 'META-USD', 'Metadium USD', '2');
insert into asset_name_symbol values (275, 'KIN-USD', 'Kin USD', '2');
insert into asset_name_symbol values (276, 'ANT-USD', 'Aragon USD', '2');
insert into asset_name_symbol values (277, 'MTL-USD', 'Metal USD', '2');
insert into asset_name_symbol values (278, 'ARK-USD', 'Ark USD', '2');
insert into asset_name_symbol values (279, 'FUN-USD', 'FunFair USD', '2');
insert into asset_name_symbol values (280, 'ARDR-USD', 'Ardor USD', '2');
insert into asset_name_symbol values (281, 'CVC-USD', 'Civic USD', '2');
insert into asset_name_symbol values (282, 'MAID-USD', 'MaidSafeCoin USD', '2');
insert into asset_name_symbol values (283, 'KMD-USD', 'Komodo USD', '2');
insert into asset_name_symbol values (284, 'VLX-USD', 'Velas USD', '2');
insert into asset_name_symbol values (285, 'WAN-USD', 'Wanchain USD', '2');
insert into asset_name_symbol values (286, 'MED-USD', 'MediBlocQRC20 USD', '2');
insert into asset_name_symbol values (287, 'COTI-USD', 'COTI USD', '2');
insert into asset_name_symbol values (288, 'HIVE-USD', 'Hive USD', '2');
insert into asset_name_symbol values (289, 'BTS-USD', 'BitShares USD', '2');
insert into asset_name_symbol values (290, 'SRM-USD', 'Serum USD', '2');
insert into asset_name_symbol values (291, 'BTM-USD', 'Bytom USD', '2');
insert into asset_name_symbol values (292, 'STRAX-USD', 'Stratis USD', '2');
insert into asset_name_symbol values (293, 'GNO-USD', 'Gnosis USD', '2');
insert into asset_name_symbol values (294, 'XHV-USD', 'HavenProtocol USD', '2');
insert into asset_name_symbol values (295, 'BCD-USD', 'BitcoinDiamond USD', '2');
insert into asset_name_symbol values (296, 'SYS-USD', 'Syscoin USD', '2');
insert into asset_name_symbol values (297, 'TOMO-USD', 'TomoChain USD', '2');
insert into asset_name_symbol values (298, 'RLC-USD', 'iExecRLC USD', '2');
insert into asset_name_symbol values (299, 'IRIS-USD', 'IRISnet USD', '2');
insert into asset_name_symbol values (300, 'MLN-USD', 'Melon USD', '2');
insert into asset_name_symbol values (301, 'TT-USD', 'ThunderToken USD', '2');
insert into asset_name_symbol values (302, 'RDD-USD', 'ReddCoin USD', '2');
insert into asset_name_symbol values (303, 'HNS-USD', 'Handshake USD', '2');
insert into asset_name_symbol values (304, 'MWC-USD', 'MimbleWimbleCoin USD', '2');
insert into asset_name_symbol values (305, 'DNT-USD', 'district0x USD', '2');
insert into asset_name_symbol values (306, 'PAC-USD', 'PACGlobal USD', '2');
insert into asset_name_symbol values (307, 'HNC-USD', 'Helleniccoin USD', '2');
insert into asset_name_symbol values (308, 'AION-USD', 'Aion USD', '2');
insert into asset_name_symbol values (309, 'PHA-USD', 'PhalaNetwork USD', '2');
insert into asset_name_symbol values (310, 'NRG-USD', 'Energi USD', '2');
insert into asset_name_symbol values (311, 'PPT-USD', 'Populous USD', '2');
insert into asset_name_symbol values (312, 'ADX-USD', 'AdEx USD', '2');
insert into asset_name_symbol values (313, 'GAS-USD', 'Gas USD', '2');
insert into asset_name_symbol values (314, 'MARO-USD', 'Maro USD', '2');
insert into asset_name_symbol values (315, 'NYE-USD', 'NewYorkExchange USD', '2');
insert into asset_name_symbol values (316, 'VRA-USD', 'Verasity USD', '2');
insert into asset_name_symbol values (317, 'DIVI-USD', 'Divi USD', '2');
insert into asset_name_symbol values (318, 'VSYS-USD', 'VSystems USD', '2');
insert into asset_name_symbol values (319, 'SAPP-USD', 'Sapphire USD', '2');
insert into asset_name_symbol values (320, 'WTC-USD', 'Waltonchain USD', '2');
insert into asset_name_symbol values (321, 'LBC-USD', 'LBRYCredits USD', '2');
insert into asset_name_symbol values (322, 'ABBC-USD', 'ABBCCoin USD', '2');
insert into asset_name_symbol values (323, 'WOZX-USD', 'EFFORCE USD', '2');
insert into asset_name_symbol values (324, 'MONA-USD', 'MonaCoin USD', '2');
insert into asset_name_symbol values (325, 'CRU-USD', 'Crust USD', '2');
insert into asset_name_symbol values (326, 'BCN-USD', 'Bytecoin USD', '2');
insert into asset_name_symbol values (327, 'ELA-USD', 'Elastos USD', '2');
insert into asset_name_symbol values (328, 'ZNN-USD', 'Zenon USD', '2');
insert into asset_name_symbol values (329, 'GRN-USD', 'GreenPower USD', '2');
insert into asset_name_symbol values (330, 'PCX-USD', 'ChainX USD', '2');
insert into asset_name_symbol values (331, 'ATRI-USD', 'AtariToken USD', '2');
insert into asset_name_symbol values (332, 'DAG-USD', 'Constellation USD', '2');
insert into asset_name_symbol values (333, 'BEAM-USD', 'Beam USD', '2');
insert into asset_name_symbol values (334, 'NKN-USD', 'NKN USD', '2');
insert into asset_name_symbol values (335, 'NULS-USD', 'NULS USD', '2');
insert into asset_name_symbol values (336, 'XNC-USD', 'XeniosCoin USD', '2');
insert into asset_name_symbol values (337, 'MASS-USD', 'Massnet USD', '2');
insert into asset_name_symbol values (338, 'FIRO-USD', 'Firo USD', '2');
insert into asset_name_symbol values (339, 'EMC2-USD', 'Einsteinium USD', '2');
insert into asset_name_symbol values (340, 'PIVX-USD', 'PIVX USD', '2');
insert into asset_name_symbol values (341, 'NXS-USD', 'Nexus USD', '2');
insert into asset_name_symbol values (342, 'GRS-USD', 'Groestlcoin USD', '2');
insert into asset_name_symbol values (343, 'REV-USD', 'RChain USD', '2');
insert into asset_name_symbol values (344, 'JUL-USD', 'Joule USD', '2');
insert into asset_name_symbol values (345, 'NIM-USD', 'Nimiq USD', '2');
insert into asset_name_symbol values (346, 'AXEL-USD', 'AXEL USD', '2');
insert into asset_name_symbol values (347, 'WICC-USD', 'WaykiChain USD', '2');
insert into asset_name_symbol values (348, 'GO-USD', 'GoChain USD', '2');
insert into asset_name_symbol values (349, 'CTXC-USD', 'Cortex USD', '2');
insert into asset_name_symbol values (350, 'CNX-USD', 'Cryptonex USD', '2');
insert into asset_name_symbol values (351, 'OBSR-USD', 'Observer USD', '2');
insert into asset_name_symbol values (352, 'NAS-USD', 'Nebulas USD', '2');
insert into asset_name_symbol values (353, 'KDA-USD', 'Kadena USD', '2');
insert into asset_name_symbol values (354, 'GNT-USD', 'Golem USD', '2');
insert into asset_name_symbol values (355, 'LOKI-USD', 'Loki USD', '2');
insert into asset_name_symbol values (356, 'APL-USD', 'ApolloCurrency USD', '2');
insert into asset_name_symbol values (357, 'BDX-USD', 'Beldex USD', '2');
insert into asset_name_symbol values (358, 'GXC-USD', 'GXChain USD', '2');
insert into asset_name_symbol values (359, 'FSN-USD', 'Fusion USD', '2');
insert into asset_name_symbol values (360, 'VITE-USD', 'VITE USD', '2');
insert into asset_name_symbol values (361, 'FIO-USD', 'FIOProtocol USD', '2');
insert into asset_name_symbol values (362, 'ERG-USD', 'Ergo USD', '2');
insert into asset_name_symbol values (363, 'AE-USD', 'Aeternity USD', '2');
insert into asset_name_symbol values (364, 'SKY-USD', 'Skycoin USD', '2');
insert into asset_name_symbol values (365, 'XLT-USD', 'Nexalt USD', '2');
insert into asset_name_symbol values (366, 'VITAE-USD', 'Vitae USD', '2');
insert into asset_name_symbol values (367, 'ARRR-USD', 'PirateChain USD', '2');
insert into asset_name_symbol values (368, 'MCO-USD', 'MCO USD', '2');
insert into asset_name_symbol values (369, 'SBD-USD', 'SteemDollars USD', '2');
insert into asset_name_symbol values (370, 'MHC-USD', 'MetaHash USD', '2');
insert into asset_name_symbol values (371, 'DCN-USD', 'Dentacoin USD', '2');
insert into asset_name_symbol values (372, 'HC-USD', 'HyperCash USD', '2');
insert into asset_name_symbol values (373, 'NXT-USD', 'Nxt USD', '2');
insert into asset_name_symbol values (374, 'NAV-USD', 'NavCoin USD', '2');
insert into asset_name_symbol values (375, 'GAME-USD', 'GameCredits USD', '2');
insert into asset_name_symbol values (376, 'NEBL-USD', 'Neblio USD', '2');
insert into asset_name_symbol values (377, 'CSC-USD', 'CasinoCoin USD', '2');
insert into asset_name_symbol values (378, 'XSN-USD', 'Stakenet USD', '2');
insert into asset_name_symbol values (379, 'RBTC-USD', 'RSKSmartBitcoin USD', '2');
insert into asset_name_symbol values (380, 'XZC-USD', 'Zcoin USD', '2');
insert into asset_name_symbol values (381, 'GRIN-USD', 'Grin USD', '2');
insert into asset_name_symbol values (382, 'RINGX-USD', 'RINGXPLATFORM USD', '2');
insert into asset_name_symbol values (383, 'PAI-USD', 'ProjectPai USD', '2');
insert into asset_name_symbol values (384, 'KRT-USD', 'TerraKRW USD', '2');
insert into asset_name_symbol values (385, 'BIP-USD', 'MinterNetwork USD', '2');
insert into asset_name_symbol values (386, 'SERO-USD', 'SuperZero USD', '2');
insert into asset_name_symbol values (387, 'DMCH-USD', 'DARMACash USD', '2');
insert into asset_name_symbol values (388, 'STRAT-USD', 'Stratis USD', '2');
insert into asset_name_symbol values (389, 'AMB-USD', 'Ambrosus USD', '2');
insert into asset_name_symbol values (390, 'VTC-USD', 'Vertcoin USD', '2');
insert into asset_name_symbol values (391, 'DERO-USD', 'Dero USD', '2');
insert into asset_name_symbol values (392, 'DGD-USD', 'DigixDAO USD', '2');
insert into asset_name_symbol values (393, 'PI-USD', 'PCHAIN USD', '2');
insert into asset_name_symbol values (394, 'VERI-USD', 'Veritaseum USD', '2');
insert into asset_name_symbol values (395, 'QASH-USD', 'QASH USD', '2');
insert into asset_name_symbol values (396, 'SALT-USD', 'SALT USD', '2');
insert into asset_name_symbol values (397, 'ETP-USD', 'MetaverseETP USD', '2');
insert into asset_name_symbol values (398, 'POA-USD', 'POANetwork USD', '2');
insert into asset_name_symbol values (399, 'CUT-USD', 'CUTcoin USD', '2');
insert into asset_name_symbol values (400, 'PAY-USD', 'TenX USD', '2');
insert into asset_name_symbol values (401, 'VIA-USD', 'Viacoin USD', '2');
insert into asset_name_symbol values (402, 'DYN-USD', 'Dynamic USD', '2');
insert into asset_name_symbol values (403, 'GBYTE-USD', 'Obyte USD', '2');
insert into asset_name_symbol values (404, 'HPB-USD', 'HighPerformanceBlockchain USD', '2');
insert into asset_name_symbol values (405, 'ADK-USD', 'AidosKuneen USD', '2');
insert into asset_name_symbol values (406, 'BLOCK-USD', 'Blocknet USD', '2');
insert into asset_name_symbol values (407, 'BHD-USD', 'BitcoinHD USD', '2');
insert into asset_name_symbol values (408, 'WGR-USD', 'Wagerr USD', '2');
insert into asset_name_symbol values (409, 'SFT-USD', 'SafexToken USD', '2');
insert into asset_name_symbol values (410, 'SNM-USD', 'SONM USD', '2');
insert into asset_name_symbol values (411, 'LYNX-USD', 'Lynx USD', '2');
insert into asset_name_symbol values (412, 'NVT-USD', 'NerveNetwork USD', '2');
insert into asset_name_symbol values (413, 'QRL-USD', 'QuantumResistantLedger USD', '2');
insert into asset_name_symbol values (414, 'NMC-USD', 'Namecoin USD', '2');
insert into asset_name_symbol values (415, 'CMT1-USD', 'CyberMiles USD', '2');
insert into asset_name_symbol values (416, 'ZEL-USD', 'ZelCash USD', '2');
insert into asset_name_symbol values (417, 'TRUE-USD', 'TrueChain USD', '2');
insert into asset_name_symbol values (418, 'FCT-USD', 'Factom USD', '2');
insert into asset_name_symbol values (419, 'SNGLS-USD', 'SingularDTV USD', '2');
insert into asset_name_symbol values (420, 'YOYOW-USD', 'YOYOW USD', '2');
insert into asset_name_symbol values (421, 'DNA1-USD', 'MetaverseDualchainNetworkArchitecture USD', '2');
insert into asset_name_symbol values (422, 'MAN-USD', 'MatrixAINetwork USD', '2');
insert into asset_name_symbol values (423, 'BTC2-USD', 'Bitcoin2 USD', '2');
insert into asset_name_symbol values (424, 'XDN-USD', 'DigitalNote USD', '2');
insert into asset_name_symbol values (425, 'ACH-USD', 'AlchemyPay USD', '2');
insert into asset_name_symbol values (426, 'ACT-USD', 'Achain USD', '2');
insert into asset_name_symbol values (427, 'VAL1-USD', 'Validity USD', '2');
insert into asset_name_symbol values (428, 'UBQ-USD', 'Ubiq USD', '2');
insert into asset_name_symbol values (429, 'HTML-USD', 'HTMLCOIN USD', '2');
insert into asset_name_symbol values (430, 'CET-USD', 'CoinExToken USD', '2');
insert into asset_name_symbol values (431, 'PPC-USD', 'Peercoin USD', '2');
insert into asset_name_symbol values (432, 'BURST-USD', 'Burst USD', '2');
insert into asset_name_symbol values (433, 'FLO-USD', 'FLO USD', '2');
insert into asset_name_symbol values (434, 'PZM-USD', 'PRIZM USD', '2');
insert into asset_name_symbol values (435, 'ZANO-USD', 'Zano USD', '2');
insert into asset_name_symbol values (436, 'GLEEC-USD', 'Gleec USD', '2');
insert into asset_name_symbol values (437, 'CHI-USD', 'Xaya USD', '2');
insert into asset_name_symbol values (438, 'BPS-USD', 'BitcoinPoS USD', '2');
insert into asset_name_symbol values (439, 'NIX-USD', 'NIX USD', '2');
insert into asset_name_symbol values (440, 'BHP-USD', 'BHPCoin USD', '2');
insert into asset_name_symbol values (441, 'AYA-USD', 'Aryacoin USD', '2');
insert into asset_name_symbol values (442, 'ZYN-USD', 'Zynecoin USD', '2');
insert into asset_name_symbol values (443, 'PHR-USD', 'Phore USD', '2');
insert into asset_name_symbol values (444, 'SMART-USD', 'SmartCash USD', '2');
insert into asset_name_symbol values (445, 'PART-USD', 'Particl USD', '2');
insert into asset_name_symbol values (446, 'FO-USD', 'FIBOS USD', '2');
insert into asset_name_symbol values (447, 'DMD-USD', 'Diamond USD', '2');
insert into asset_name_symbol values (448, 'PLC-USD', 'PLATINCOIN USD', '2');
insert into asset_name_symbol values (449, 'CTC-USD', 'CreditTagChain USD', '2');
insert into asset_name_symbol values (450, 'TERA-USD', 'TERA USD', '2');
insert into asset_name_symbol values (451, 'MIR-USD', 'MIRCOIN USD', '2');
insert into asset_name_symbol values (452, 'XMC-USD', 'MoneroClassic USD', '2');
insert into asset_name_symbol values (453, 'WINGS-USD', 'Wings USD', '2');
insert into asset_name_symbol values (454, 'XRC-USD', 'BitcoinRhodium USD', '2');
insert into asset_name_symbol values (455, 'XMY-USD', 'Myriad USD', '2');
insert into asset_name_symbol values (456, 'INSTAR-USD', 'InsightsNetwork USD', '2');
insert into asset_name_symbol values (457, 'FTC-USD', 'Feathercoin USD', '2');
insert into asset_name_symbol values (458, 'AEON-USD', 'Aeon USD', '2');
insert into asset_name_symbol values (459, 'NLG-USD', 'Gulden USD', '2');
insert into asset_name_symbol values (460, 'SCP-USD', 'ScPrime USD', '2');
insert into asset_name_symbol values (461, 'HTDF-USD', 'OrientWalt USD', '2');
insert into asset_name_symbol values (462, 'TAAS-USD', 'TaaS USD', '2');
insert into asset_name_symbol values (463, 'MOON-USD', 'Mooncoin USD', '2');
insert into asset_name_symbol values (464, 'LCC-USD', 'LitecoinCash USD', '2');
insert into asset_name_symbol values (465, 'IDNA-USD', 'Idena USD', '2');
insert into asset_name_symbol values (466, 'INT-USD', 'InternetNodeToken USD', '2');
insert into asset_name_symbol values (467, 'NYZO-USD', 'Nyzo USD', '2');
insert into asset_name_symbol values (468, 'ILC-USD', 'ILCoin USD', '2');
insert into asset_name_symbol values (469, 'GHOST1-USD', 'GHOST USD', '2');
insert into asset_name_symbol values (470, 'XST-USD', 'Stealth USD', '2');
insert into asset_name_symbol values (471, 'VEX-USD', 'Vexanium USD', '2');
insert into asset_name_symbol values (472, 'OTO-USD', 'OTOCASH USD', '2');
insert into asset_name_symbol values (473, 'FAIR-USD', 'FairCoin USD', '2');
insert into asset_name_symbol values (474, 'BPC-USD', 'BackPackerCoin USD', '2');
insert into asset_name_symbol values (475, 'CRW-USD', 'Crown USD', '2');
insert into asset_name_symbol values (476, 'DIME-USD', 'Dimecoin USD', '2');
insert into asset_name_symbol values (477, 'POLIS-USD', 'Polis USD', '2');
insert into asset_name_symbol values (478, 'BLK-USD', 'BlackCoin USD', '2');
insert into asset_name_symbol values (479, 'DTEP-USD', 'DECOIN USD', '2');
insert into asset_name_symbol values (480, 'GRC-USD', 'GridCoin USD', '2');
insert into asset_name_symbol values (481, 'IOC-USD', 'IOCoin USD', '2');
insert into asset_name_symbol values (482, 'VIN-USD', 'VINchain USD', '2');
insert into asset_name_symbol values (483, 'CURE-USD', 'Curecoin USD', '2');
insert into asset_name_symbol values (484, 'SUB-USD', 'Substratum USD', '2');
insert into asset_name_symbol values (485, 'PMEER-USD', 'Pmeer USD', '2');
insert into asset_name_symbol values (486, 'RADS-USD', 'Radium USD', '2');
insert into asset_name_symbol values (487, 'OWC-USD', 'ODUWA USD', '2');
insert into asset_name_symbol values (488, 'HYC-USD', 'HYCON USD', '2');
insert into asset_name_symbol values (489, 'ZVC-USD', 'ZVCHAIN USD', '2');
insert into asset_name_symbol values (490, 'QRK-USD', 'Quark USD', '2');
insert into asset_name_symbol values (491, 'GCC1-USD', 'GlobalCryptocurrency USD', '2');
insert into asset_name_symbol values (492, 'SONO1-USD', 'SonoCoin USD', '2');
insert into asset_name_symbol values (493, 'XAS-USD', 'Asch USD', '2');
insert into asset_name_symbol values (494, 'MBC-USD', 'MicroBitcoin USD', '2');
insert into asset_name_symbol values (495, 'BCA-USD', 'BitcoinAtom USD', '2');
insert into asset_name_symbol values (496, 'MGO-USD', 'MobileGo USD', '2');
insert into asset_name_symbol values (497, 'XBY-USD', 'XTRABYTES USD', '2');
insert into asset_name_symbol values (498, 'CPS-USD', 'Capricoin USD', '2');
insert into asset_name_symbol values (499, 'ERK-USD', 'EurekaCoin USD', '2');
insert into asset_name_symbol values (500, 'EDG-USD', 'Edgeless USD', '2');
insert into asset_name_symbol values (501, 'DDK-USD', 'DDKoin USD', '2');
insert into asset_name_symbol values (502, 'USNBT-USD', 'NuBits USD', '2');
insert into asset_name_symbol values (503, 'GHOST-USD', 'GHOSTPRISM USD', '2');
insert into asset_name_symbol values (504, 'NPC-USD', 'NPCoin USD', '2');
insert into asset_name_symbol values (505, 'OURO-USD', 'Ouroboros USD', '2');
insert into asset_name_symbol values (506, 'HSS-USD', 'Hashshare USD', '2');
insert into asset_name_symbol values (507, 'DEV-USD', 'DeviantCoin USD', '2');
insert into asset_name_symbol values (508, 'FRST-USD', 'FirstCoin USD', '2');
insert into asset_name_symbol values (509, 'ATB-USD', 'ATBCoin USD', '2');
insert into asset_name_symbol values (510, 'COMP1-USD', 'CompoundCoin USD', '2');
insert into asset_name_symbol values (511, 'ALIAS-USD', 'Alias USD', '2');
insert into asset_name_symbol values (512, 'UNO-USD', 'Unobtanium USD', '2');
insert into asset_name_symbol values (513, 'EDC-USD', 'EDCBlockchain USD', '2');
insert into asset_name_symbol values (514, 'ECC-USD', 'ECC USD', '2');
insert into asset_name_symbol values (515, 'ECA-USD', 'Electra USD', '2');
insert into asset_name_symbol values (516, 'LKK-USD', 'Lykke USD', '2');
insert into asset_name_symbol values (517, 'NLC2-USD', 'NoLimitCoin USD', '2');
insert into asset_name_symbol values (518, 'BONO-USD', 'Bonorum USD', '2');
insert into asset_name_symbol values (519, 'CLAM-USD', 'Clams USD', '2');
insert into asset_name_symbol values (520, 'COLX-USD', 'ColossusXT USD', '2');
insert into asset_name_symbol values (521, 'MOAC-USD', 'MOAC USD', '2');
insert into asset_name_symbol values (522, 'FLASH-USD', 'Flash USD', '2');
insert into asset_name_symbol values (523, 'DUN-USD', 'DuneNetwork USD', '2');
insert into asset_name_symbol values (524, 'RBY-USD', 'Rubycoin USD', '2');
insert into asset_name_symbol values (525, 'AIB-USD', 'AdvancedInternetBlocks USD', '2');
insert into asset_name_symbol values (526, 'XUC-USD', 'ExchangeUnion USD', '2');
insert into asset_name_symbol values (527, 'MINT-USD', 'MintCoin USD', '2');
insert into asset_name_symbol values (528, 'MRX-USD', 'MetrixCoin USD', '2');
insert into asset_name_symbol values (529, 'TUBE-USD', 'BitTube USD', '2');
insert into asset_name_symbol values (530, 'SCC3-USD', 'StakeCubeCoin USD', '2');
insert into asset_name_symbol values (531, 'DCY-USD', 'Dinastycoin USD', '2');
insert into asset_name_symbol values (532, 'XNS1-USD', 'Insolar USD', '2');
insert into asset_name_symbol values (533, 'RSTR-USD', 'Ondori USD', '2');
insert into asset_name_symbol values (534, 'MTC2-USD', 'Metacoin USD', '2');
insert into asset_name_symbol values (535, 'MIDAS-USD', 'Midas USD', '2');
insert into asset_name_symbol values (536, 'SLS-USD', 'SaluS USD', '2');
insert into asset_name_symbol values (537, 'SHIFT-USD', 'Shift USD', '2');
insert into asset_name_symbol values (538, 'CCA-USD', 'CounosCoin USD', '2');
insert into asset_name_symbol values (539, 'JDC-USD', 'JDCoin USD', '2');
insert into asset_name_symbol values (540, 'XLQ-USD', 'ALQO USD', '2');
insert into asset_name_symbol values (541, 'BTX-USD', 'Bitcore USD', '2');
insert into asset_name_symbol values (542, 'XCP-USD', 'Counterparty USD', '2');
insert into asset_name_symbol values (543, 'LRG-USD', 'LargoCoin USD', '2');
insert into asset_name_symbol values (544, 'BRC-USD', 'BaerChain USD', '2');
insert into asset_name_symbol values (545, 'YEP-USD', 'YEPCOIN USD', '2');
insert into asset_name_symbol values (546, 'VBK-USD', 'VeriBlock USD', '2');
